"""Reproducible scenario model using shipped Lua configs. Not observed retention."""
from pathlib import Path
import random,statistics,json
from lupa import LuaRuntime
ROOT=Path(__file__).resolve().parents[1]
lua=LuaRuntime(unpack_returned_tuples=True)
lua.execute('Color3={fromRGB=function() return {} end}')
E=lua.execute((ROOT/'src/shared/Config/EconomyConfig.lua').read_text())
M=lua.execute((ROOT/'src/shared/Config/MachineConfig.lua').read_text())
ids=list(M.Order.values());weights=[M.ById[x].SpawnWeight for x in ids]
incomes={id:M.ById[id].BaseIncome for id in ids}
level_factor=E.IncomePerLevel
costs={key:[E.cost(key,level) for level in range(21)] for key in E.UpgradeOrder.values()}
def income_for(inventory,level,double):return sum(incomes[x] for x in inventory)*(1+level_factor*level)*(2 if double else 1)
profiles={'New':(90,100,1),'Average':(65,75,3),'Efficient':(50,55,6)}
minutes=[1,3,5,8,10,15,20,25,30,45]
# A player who improves income, then utility/storage, then saves for the first annex.
plan=['Income','Speed','Carry','Slots','Income','Expansion','Slots','Income','Speed','Carry','Expansion','Income','Slots','Income','Expansion']
def simulate(profile,double,seed,greedy=False):
 first,interval,choices=profiles[profile];rng=random.Random(seed)
 balance=0.;earned=0.;inventory=['radio'];levels={k:0 for k in E.UpgradeOrder.values()};purchases=[];cursor=0;frames={}
 for t in range(1,2701):
  income=income_for(inventory,levels['Income'],double)
  balance+=income;earned+=income
  if t>=first and (t-first)%interval==0:
   candidates=rng.choices(ids,weights=weights,k=choices)
   item=max(candidates,key=lambda x:incomes[x])
   capacity=E.BaseSlots+levels['Slots']*E.SlotsPerLevel+levels['Expansion']*E.ExpansionSlots
   if len(inventory)<capacity:inventory.append(item)
   else:
    # Protected starter stays; players selectively replace their weakest other machine.
    index=min(range(1,len(inventory)),key=lambda i:incomes[inventory[i]])
    if incomes[item]>incomes[inventory[index]]:inventory[index]=item
   available=[k for k in levels if levels[k]<E.Upgrades[k].Max]
   if (cursor<len(plan) and not greedy) or (greedy and available):
    key=min(available,key=lambda k:costs[k][levels[k]]) if greedy else plan[cursor];cost=costs[key][levels[key]]
    if balance>=cost:
     balance-=cost;levels[key]+=1;purchases.append((t,key));cursor+=1
  if t%60==0 and t//60 in minutes:
   frames[t//60]={'Machines':len(inventory),'Income':income_for(inventory,levels['Income'],double),'Earned':earned,'Balance':balance,'Purchases':len(purchases)}
 return frames,purchases
all_results={};rows=[]
for profile in profiles:
 for double in [False,True]:
  runs=[simulate(profile,double,seed) for seed in range(200)]
  key=profile+(' / 2X' if double else ' / free')
  firsts=[p[0][0] for _,p in runs if p]
  annex=[next((t for t,k in p if k=='Expansion'),2701) for _,p in runs]
  rows.append((key,statistics.median(firsts),statistics.median(annex),min(firsts),max(firsts)))
  all_results[key]={m:{field:round(statistics.median(f[m][field] for f,p in runs),2) for field in ['Machines','Income','Earned','Balance','Purchases']} for m in minutes}
lines=['# Economy V2 — calculated scenarios','',
'Generated by `python tools/simulate_economy.py` from the shipped EconomyConfig and MachineConfig. 200 seeded runs per scenario, 1-second steps, 45-minute horizon. Values below are medians, not measured players or optimal retention guarantees.','',
'## Assumptions','',
'New player: first delivery at 90s, then every 100s; samples one weighted machine. Average: 65s then every 75s; chooses the highest income of three weighted candidates. Efficient: 50s then every 55s; chooses among six. Models spare salvage availability, no theft, no competing players, no deaths, no AFK pauses and no route speed improvement from purchased upgrades. Strong selection may overestimate real contested-server income; fixed intervals may underestimate movement benefits.','',
'At capacity, replace the weakest non-starter only if the delivered machine is better. Purchases occur at delivery, at most one per visit. Scripted strategy: '+', '.join(plan)+'. This is one choice policy, not a forecast of all choices. Fresh accounts have 0 Scrap, 0 Cores and no upgrades; old accounts retain balances and progress.','',
'## First decisions','',
'| Scenario | First upgrade, median | First annex, median | First upgrade min–max |','|---|---:|---:|---:|']
for key,first,annex,lo,hi in rows:
 lines.append(f'| {key} | {first/60:.1f} min | {annex/60:.1f} min | {lo/60:.1f}–{hi/60:.1f} min |')
lines+=['','Annex values beyond 45 minutes mean not reached during the simulated horizon. Random rare finds produce outliers; these are not guarantees.','',
'## Economy constants','',
'Starter: 0.30 Scrap/sec. Income = sum(machine base incomes) × (1 + 0.12 × Income level) × (2 with pass, otherwise 1). No compounded income upgrades. Price = floor(base × growth^current level).','',
'| Upgrade | Base price | Growth | Levels |','|---|---:|---:|---:|']
for key in E.UpgradeOrder.values():
 d=E.Upgrades[key];lines.append(f'| {key} | {d.Base} | {d.Growth} | {d.Max} |')
lines+=['','| Machine | Base Scrap/sec | Spawn weight |','|---|---:|---:|']
for id in ids:
 d=M.ById[id];lines.append(f'| {d.DisplayName} | {d.BaseIncome} | {d.SpawnWeight} |')
for key,result in all_results.items():
 lines+=['',f'## {key}','','| Minute | Machines | Scrap/sec | Total earned | Unspent Scrap | Purchases |','|---:|---:|---:|---:|---:|---:|']
 for m,v in result.items():lines.append('| '+ ' | '.join(map(str,[m,*v.values()]))+' |')
lines+=['','## Core economy','',
'Four daily contracts: deliver five (10 Cores), deliver two Rare+ (12), buy two upgrades (8), inspect three distinct landmarks (10). Maximum 40/day; no idle-time quest or login payout. First style is 30 Cores, second 70, third 120. An active player doing three contracts can reach 30/day; with only two easy contracts, expect 18–20/day. These are reward-budget calculations, not measured completion rates.','',
'All three styles total 220 Cores. At 40/day this takes six daily sets; at 20/day eleven. An 80-Core pack can buy Teal or Violet; both together cost 100. A 250-Core pack covers the whole initial catalog. 600, 1,400 and 3,000 remain configured but hidden until more content supports their value. Paid purchases remain disabled. No luck/loot or paid random outcomes.','',
'## Limits and interpretation','',
'Movement caps 20 walking / 16 carrying preserve travel. Capacity: 4 + 2 per slot level + 2 per expansion + 5 with pass, capped at 24; migrated accounts retain a minimum capacity floor. Major goals continue beyond the first annex. Evaluate real first-pickup, first-placement, first-upgrade, quest and session funnels before revising these assumptions.','',
'Roblox discovery guidance emphasizes early bounce, repeat play and engagement; this model does not optimize an algorithm: https://create.roblox.com/docs/discovery','']
(ROOT/'docs/ECONOMY_V2.md').write_text('\n'.join(lines))
(ROOT/'docs/economy-simulation.json').write_text(json.dumps(all_results,indent=2)+'\n')
for row in rows:print(row)

# Alternate purchase policy stresses cheaper upgrade spam, not just the planned annex saver.
greedy_runs=[simulate('Efficient',True,seed,True) for seed in range(200)]
max_levels=sum(E.Upgrades[key].Max for key in E.UpgradeOrder.values())
completed=sum(len(p)>=max_levels for _,p in greedy_runs)
median_count=statistics.median(len(p) for _,p in greedy_runs)
with (ROOT/'docs/ECONOMY_V2.md').open('a') as f:
 f.write(f"\n## Greedy 2X stress case\n\nAn alternate efficient-player policy buys the cheapest available upgrade on each delivery rather than saving for the annex. Across 200 seeded 45-minute runs, median purchases = {median_count} of {max_levels} possible levels; {completed}/200 runs completed the full ladder. This is a stress scenario, not proof against every player strategy.\n")
print('Greedy 2X:',median_count,'of',max_levels,'levels;',completed,'/200 finish by 45m')
